sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
- npm install -g angular-cli
- npm install
- npm i -g angular-cli-ghpages
- ng build --prod --base-href "https://adibro500.github.io/spoonkart-ng/"
- angular-cli-ghpages --repo=https://GHToken@github.com/adibro500/spoonkart-ng.git --name="adibro500" --email=ammanabrolu.aditya@gmail.com

