sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
- npm install -g angular-cli
- npm install
- npm i -g angular-cli-ghpages
- npm install travis-encrypt -g
- travis-encrypt -r adibro/spoonkart-ng GHToken=e4eef28a2749bb7aa7528de59963104c9d7c70c0
- ng build --env=prod --aot --base-href "https://adibro500.github.io/spoonkart-ng/"
- ngh --repo=https://GHToken@github.com/adibro500/spoonkart-ng.git --no-silent

